version: '3.3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    entrypoint: python /app/src/scrapper/wsgi.py

  celery:
    build: .
    depends_on:
      - db
      - redis
    entrypoint: celery worker -l info -A scrapper.tasks.celery_app --concurrency=10


  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  redis:
    image: redis:4.0.5-alpine

    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"


# Names our volume
volumes:
  my-db:
  redis-data:
#  web:
#
#networks:
#  default:
#    external: true
